import { useState } from 'react';

export const DISCLAIMERS = {
  global: {
    title: 'Terms of Use & General Disclaimer',
    body: `Mech.gg ("the Service") is provided for informational and entertainment purposes only. By using Mech.gg you agree to these terms.

The analysis provided by Mech.gg is generated by automated statistical simulation based on uploaded file metadata and is NOT a substitute for professional coaching, sports psychology, or expert evaluation. Results are approximate and should not be relied upon for competitive decisions, tournament preparation, or professional development without independent verification.

Mech.gg makes no warranties, express or implied, regarding the accuracy, completeness, or fitness for any particular purpose of any analysis, score, or recommendation provided. Use of this service is at your own risk.

You must be 13 years of age or older to use this service. If you are under 18, you must have parental consent.

We reserve the right to modify, suspend, or discontinue any part of this service at any time without notice.`,
  },
  analysis: {
    title: 'Analysis Disclaimer',
    body: `The Mechanical Index score and all dimension scores are generated by a statistical simulation engine. They are NOT produced by real-time video analysis, AI vision models, or professional human review.

Scores are derived from uploaded file properties and are intended to provide a motivational framework and general performance benchmark only. The same clip uploaded twice may produce identical scores. Scores should not be used to assess actual competitive skill level for tournament seeding, team selection, or professional evaluation.

Habit detection descriptions are illustrative coaching suggestions based on general gameplay principles, not observations of your specific footage.

Mech.gg accepts no liability for decisions made based on analysis results.`,
  },
  community: {
    title: 'Community & User Content Disclaimer',
    body: `Content posted by users in the Community section and Forum represents the personal opinions of individual users and does not represent the views of Mech.gg or its operators.

Mech.gg does not verify the accuracy, expertise, or qualifications of any user posting content. Do not rely on community posts for medical, psychological, physical training, or professional decisions without independent verification.

By posting content, you grant Mech.gg a non-exclusive, royalty-free license to display and distribute that content within the service. You retain ownership of your content.

Content that is abusive, defamatory, or violates applicable laws will be removed. Report violations using the report feature.`,
  },
  coaching: {
    title: 'Coaching Services Disclaimer',
    body: `Coach profiles listed on Mech.gg are created and managed by independent users. Mech.gg does NOT verify, endorse, or guarantee the qualifications, credentials, experience, or quality of any coach listed on this platform.

Any coaching arrangement entered into through connections made on Mech.gg is a private agreement between the user and the coach. Mech.gg is not a party to such arrangements and accepts no liability for the quality, outcome, or disputes arising from coaching relationships.

Payment, scheduling, and terms of coaching services are solely between the coach and client. Mech.gg provides no payment processing, escrow, or dispute resolution for coaching services.

Always exercise independent judgment when selecting a coach.`,
  },
  messaging: {
    title: 'Messaging Disclaimer',
    body: `The private messaging system is provided as a convenience feature. Mech.gg does not monitor private messages except as required by law or to investigate reported violations of our terms.

Do not share sensitive personal information, financial details, passwords, or private contact information through the messaging system. Mech.gg accepts no liability for information shared through private messages.

Messages may be reviewed in response to valid legal requests or to investigate abuse reports. All communications must comply with our community guidelines and applicable law.`,
  },
  pricing: {
    title: 'Subscription & Billing Disclaimer',
    body: `Subscription plans are provided on a month-to-month basis. Analysis limits reset on the first day of each calendar month. Unused analyses do not roll over.

Plan upgrades and downgrades take effect immediately. Mech.gg does not currently process real payments — this is a demonstration platform. No actual charges will be made.

In a production deployment, all billing would be handled by a third-party payment processor. Mech.gg would not store payment card information.

Mech.gg reserves the right to change pricing and plan features at any time with reasonable notice.`,
  },
  drills: {
    title: 'Training & Drill Plan Disclaimer',
    body: `Drill plans and training recommendations provided by Mech.gg are for informational purposes only and are NOT a substitute for professional coaching, physical training guidance, or sports medicine advice.

Before beginning any training regimen, consult with appropriate professionals. Stop any drill immediately if you experience physical discomfort, eye strain, repetitive stress symptoms, or any other adverse effects.

Mech.gg accepts no liability for physical, mental, or competitive outcomes resulting from following drill recommendations. Duration and frequency recommendations are general guidelines and may not be appropriate for all individuals.`,
  },
};

export function DisclaimerBanner({ type, collapsed=true }) {
  const [open, setOpen] = useState(!collapsed);
  const d = DISCLAIMERS[type] || DISCLAIMERS.global;
  return (
    <div style={{ background:'rgba(251,191,36,0.05)', border:'1px solid rgba(251,191,36,0.2)', borderRadius:'var(--r)', marginBottom:'1.5rem', overflow:'hidden' }}>
      <button onClick={()=>setOpen(!open)} style={{ width:'100%', display:'flex', alignItems:'center', justifyContent:'space-between', padding:'0.625rem 1rem', background:'none', border:'none', cursor:'pointer', textAlign:'left' }}>
        <div style={{ display:'flex', alignItems:'center', gap:'0.5rem' }}>
          <span style={{ fontSize:'0.8rem' }}>⚖️</span>
          <span style={{ fontFamily:'var(--mono)', fontSize:'0.72rem', color:'var(--yellow)', fontWeight:700, letterSpacing:'0.05em' }}>{d.title.toUpperCase()}</span>
        </div>
        <span style={{ color:'var(--text-3)', fontSize:'0.75rem', fontFamily:'var(--mono)' }}>{open?'▲ hide':'▼ show'}</span>
      </button>
      {open && (
        <div style={{ padding:'0 1rem 1rem', fontSize:'0.78rem', color:'var(--text-3)', lineHeight:1.7, whiteSpace:'pre-line', borderTop:'1px solid rgba(251,191,36,0.15)' }}>
          <div style={{ paddingTop:'0.75rem' }}>{d.body}</div>
        </div>
      )}
    </div>
  );
}

export function GlobalLegalFooter() {
  return (
    <div style={{ borderTop:'1px solid var(--border)', marginTop:'4rem', padding:'2rem 0', fontSize:'0.75rem', color:'var(--text-3)', lineHeight:1.8 }}>
      <div style={{ maxWidth:'1100px', margin:'0 auto', padding:'0 1.5rem' }}>
        <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))', gap:'1.5rem', marginBottom:'1.5rem' }}>
          <div>
            <div style={{ fontFamily:'var(--mono)', fontSize:'0.7rem', color:'var(--text-2)', fontWeight:700, marginBottom:'0.5rem' }}>LEGAL</div>
            <div>Mech.gg is provided for entertainment and informational purposes only. Analysis results are simulated and do not represent professional evaluation of skill or performance.</div>
          </div>
          <div>
            <div style={{ fontFamily:'var(--mono)', fontSize:'0.7rem', color:'var(--text-2)', fontWeight:700, marginBottom:'0.5rem' }}>DATA & PRIVACY</div>
            <div>Gameplay clips are deleted immediately after analysis. Only numerical scores are stored. We do not sell user data. See our Privacy Policy for full details.</div>
          </div>
          <div>
            <div style={{ fontFamily:'var(--mono)', fontSize:'0.7rem', color:'var(--text-2)', fontWeight:700, marginBottom:'0.5rem' }}>CONTENT</div>
            <div>User-generated content does not represent Mech.gg's views. Coach listings are user-submitted and unverified. Use independent judgment for all coaching decisions.</div>
          </div>
        </div>
        <div style={{ textAlign:'center', borderTop:'1px solid var(--border)', paddingTop:'1rem', display:'flex', flexWrap:'wrap', justifyContent:'center', gap:'0.5rem 1.5rem' }}>
          <span>© {new Date().getFullYear()} Mech.gg — All rights reserved.</span>
          <a href="/legal" style={{ color:'var(--text-3)' }}>Terms & Refund Policy</a>
          <a href="/privacy" style={{ color:'var(--text-3)' }}>Privacy Policy</a>
          <a href="/legal" style={{ color:'var(--text-3)' }}>Age Policy</a>
          <a href="/pricing" style={{ color:'var(--text-3)' }}>Pricing</a>
          <a href="mailto:mechggofficial@gmail.com" style={{ color:'var(--text-3)' }}>mechggofficial@gmail.com</a>
          <span style={{ color:'var(--text-3)' }}>18+ · Minors with guardian supervision only</span>
        </div>
      </div>
    </div>
  );
}
